package homebrew

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"fmt"
	"io"
	"regexp"
	"strings"
	"text/template"
)

const (
	darwinARM64 = "go-argo-mcp_Darwin_arm64.tar.gz"
	darwinAMD64 = "go-argo-mcp_Darwin_x86_64.tar.gz"
	linuxARM64  = "go-argo-mcp_Linux_arm64.tar.gz"
	linuxAMD64  = "go-argo-mcp_Linux_x86_64.tar.gz"
)

var versionPattern = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$`)

type formulaData struct {
	Version     string
	DarwinARM64 string
	DarwinAMD64 string
	LinuxARM64  string
	LinuxAMD64  string
}

func ParseChecksums(reader io.Reader) (map[string]string, error) {
	checksums := map[string]string{}
	scanner := bufio.NewScanner(reader)
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) != 2 {
			return nil, fmt.Errorf("invalid checksum line %q", scanner.Text())
		}
		if !validChecksum(fields[0]) {
			return nil, fmt.Errorf("invalid SHA-256 checksum for %s", fields[1])
		}
		checksums[fields[1]] = fields[0]
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read checksums: %w", err)
	}
	return checksums, nil
}

func Render(version string, checksums map[string]string) ([]byte, error) {
	if !versionPattern.MatchString(version) {
		return nil, fmt.Errorf("invalid release version %q", version)
	}
	required := []string{darwinARM64, darwinAMD64, linuxARM64, linuxAMD64}
	for _, name := range required {
		if !validChecksum(checksums[name]) {
			return nil, fmt.Errorf("missing or invalid checksum for %s", name)
		}
	}
	data := formulaData{
		Version:     version,
		DarwinARM64: checksums[darwinARM64],
		DarwinAMD64: checksums[darwinAMD64],
		LinuxARM64:  checksums[linuxARM64],
		LinuxAMD64:  checksums[linuxAMD64],
	}
	var output bytes.Buffer
	if err := formulaTemplate.Execute(&output, data); err != nil {
		return nil, fmt.Errorf("render formula: %w", err)
	}
	return output.Bytes(), nil
}

func validChecksum(value string) bool {
	decoded, err := hex.DecodeString(value)
	return err == nil && len(decoded) == 32
}

var formulaTemplate = template.Must(template.New("formula").Parse(`# typed: false
# frozen_string_literal: true

# Generated by the go-argo-mcp release workflow. DO NOT EDIT.
class GoArgoMcp < Formula
  desc "Lightweight Go MCP server for Argo Workflows"
  homepage "https://github.com/CaliLuke/go-argo-mcp"
  version "{{ .Version }}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v{{ .Version }}/go-argo-mcp_Darwin_x86_64.tar.gz"
      sha256 "{{ .DarwinAMD64 }}"
    end
    if Hardware::CPU.arm?
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v{{ .Version }}/go-argo-mcp_Darwin_arm64.tar.gz"
      sha256 "{{ .DarwinARM64 }}"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v{{ .Version }}/go-argo-mcp_Linux_x86_64.tar.gz"
      sha256 "{{ .LinuxAMD64 }}"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CaliLuke/go-argo-mcp/releases/download/v{{ .Version }}/go-argo-mcp_Linux_arm64.tar.gz"
      sha256 "{{ .LinuxARM64 }}"
    end
  end

  def install
    bin.install "go-argo-mcp"
  end

  def caveats
    <<~EOS
      go-argo-mcp exposes Streamable HTTP at http://127.0.0.1:8080/rpc.
      Set ARGO_BASE_URL and optional ARGO_NAMESPACE before starting it.
    EOS
  end

  test do
    system bin/"go-argo-mcp", "--version"
  end
end
`))
