package argomodelgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"strings"
)

type projection struct {
	Package       string           `json:"package"`
	SourceVersion string           `json:"sourceVersion"`
	Definitions   []definitionSpec `json:"definitions"`
}

type definitionSpec struct {
	Source string      `json:"source"`
	Name   string      `json:"name"`
	Fields []fieldSpec `json:"fields"`
}

type fieldSpec struct {
	Source                string `json:"source"`
	Name                  string `json:"name"`
	GoType                string `json:"goType"`
	JSON                  string `json:"json"`
	Schema                string `json:"schema"`
	CompatibilityOverride string `json:"compatibilityOverride"`
	Extension             string `json:"extension"`
	OmitEmpty             *bool  `json:"omitEmpty"`
}

type swagger struct {
	Definitions map[string]schemaNode `json:"definitions"`
}

type schemaNode struct {
	Type                 string                `json:"type"`
	Ref                  string                `json:"$ref"`
	Properties           map[string]schemaNode `json:"properties"`
	Items                *schemaNode           `json:"items"`
	AdditionalProperties *schemaNode           `json:"additionalProperties"`
}

// Generate validates the selected projection against a Swagger document and
// returns formatted Go source. It performs no network access.
func Generate(schemaData, projectionData []byte) ([]byte, error) {
	var document swagger
	if err := json.Unmarshal(schemaData, &document); err != nil {
		return nil, fmt.Errorf("decode Swagger schema: %w", err)
	}
	var selection projection
	decoder := json.NewDecoder(bytes.NewReader(projectionData))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&selection); err != nil {
		return nil, fmt.Errorf("decode projection: %w", err)
	}
	if selection.Package == "" || len(selection.Definitions) == 0 {
		return nil, fmt.Errorf("projection must define a package and at least one definition")
	}
	for _, selectedDefinition := range selection.Definitions {
		definition, ok := document.Definitions[selectedDefinition.Source]
		if !ok {
			return nil, fmt.Errorf("definition %s is missing from Swagger", selectedDefinition.Source)
		}
		if selectedDefinition.Name == "" {
			return nil, fmt.Errorf("definition %s has no generated name", selectedDefinition.Source)
		}
		for _, field := range selectedDefinition.Fields {
			if err := validateField(document.Definitions, selectedDefinition.Source, definition, field); err != nil {
				return nil, err
			}
		}
	}

	var source strings.Builder
	fmt.Fprintf(&source, "// Code generated by go run ./cmd/generate-argo-models; DO NOT EDIT.\n")
	fmt.Fprintf(&source, "// Source: Argo Workflows %s Swagger projection.\n\n", selection.SourceVersion)
	fmt.Fprintf(&source, "package %s\n", selection.Package)
	needsJSON := false
	for _, definition := range selection.Definitions {
		for _, field := range definition.Fields {
			needsJSON = needsJSON || strings.Contains(field.GoType, "json.")
		}
	}
	if needsJSON {
		source.WriteString("\nimport \"encoding/json\"\n")
	}
	for _, definition := range selection.Definitions {
		fmt.Fprintf(&source, "\ntype %s struct {\n", definition.Name)
		for _, field := range definition.Fields {
			jsonTag := field.JSON
			if field.OmitEmpty == nil || *field.OmitEmpty {
				jsonTag += ",omitempty"
			}
			fmt.Fprintf(&source, "\t%s %s `json:\"%s\"`\n", field.Name, field.GoType, jsonTag)
		}
		source.WriteString("}\n")
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated models: %w", err)
	}
	return formatted, nil
}

func validateField(definitions map[string]schemaNode, definitionName string, definition schemaNode, field fieldSpec) error {
	if field.Name == "" || field.GoType == "" || field.JSON == "" {
		return fmt.Errorf("definition %s contains an incomplete field", definitionName)
	}
	if field.Extension != "" {
		if field.Source != "" || field.Schema != "" {
			return fmt.Errorf("extension field %s.%s must not claim a Swagger source", definitionName, field.Name)
		}
		return nil
	}
	if field.Source == "" || field.Schema == "" {
		return fmt.Errorf("field %s.%s must identify its Swagger property and schema", definitionName, field.Name)
	}
	property, ok := definition.Properties[field.Source]
	if !ok {
		return fmt.Errorf("property %s is missing from definition %s", field.Source, definitionName)
	}
	actual := describeSchema(property)
	if actual != field.Schema {
		return fmt.Errorf("property %s.%s: expected %s, found %s", definitionName, field.Source, field.Schema, actual)
	}
	ref := referencedDefinition(property)
	if ref != "" {
		if _, ok := definitions[ref]; !ok {
			return fmt.Errorf("property %s.%s references missing definition %s", definitionName, field.Source, ref)
		}
	}
	return nil
}

func describeSchema(node schemaNode) string {
	if node.Ref != "" {
		return "ref:" + strings.TrimPrefix(node.Ref, "#/definitions/")
	}
	switch node.Type {
	case "array":
		if node.Items == nil {
			return "array:<missing>"
		}
		return "array:" + describeSchema(*node.Items)
	case "object":
		if node.AdditionalProperties != nil {
			return "map:" + describeSchema(*node.AdditionalProperties)
		}
	}
	return node.Type
}

func referencedDefinition(node schemaNode) string {
	if node.Ref != "" {
		return strings.TrimPrefix(node.Ref, "#/definitions/")
	}
	if node.Items != nil {
		return referencedDefinition(*node.Items)
	}
	if node.AdditionalProperties != nil {
		return referencedDefinition(*node.AdditionalProperties)
	}
	return ""
}
