// Code generated by go run ./cmd/generate-argo-models; DO NOT EDIT.
// Source: Argo Workflows v3.7.3 Swagger projection.

package models

import "encoding/json"

type ObjectMeta struct {
	Name        string            `json:"name,omitempty"`
	Namespace   string            `json:"namespace,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

type ListMeta struct {
	Continue string `json:"continue,omitempty"`
}

type Parameter struct {
	Name      string          `json:"name,omitempty"`
	Value     json.RawMessage `json:"value,omitempty"`
	Default   json.RawMessage `json:"default,omitempty"`
	ValueFrom json.RawMessage `json:"valueFrom,omitempty"`
}

type Arguments struct {
	Parameters []Parameter `json:"parameters,omitempty"`
}

type Outputs struct {
	Parameters []Parameter `json:"parameters,omitempty"`
}

type Template struct {
	Name string `json:"name,omitempty"`
}

type WorkflowSpec struct {
	Arguments  Arguments  `json:"arguments,omitempty"`
	Entrypoint string     `json:"entrypoint,omitempty"`
	Templates  []Template `json:"templates,omitempty"`
}

type WorkflowStatus struct {
	Phase      string  `json:"phase,omitempty"`
	Progress   string  `json:"progress,omitempty"`
	StartedAt  string  `json:"startedAt,omitempty"`
	FinishedAt string  `json:"finishedAt,omitempty"`
	Message    string  `json:"message,omitempty"`
	Outputs    Outputs `json:"outputs,omitempty"`
}

type Workflow struct {
	Metadata ObjectMeta     `json:"metadata,omitempty"`
	Spec     WorkflowSpec   `json:"spec,omitempty"`
	Status   WorkflowStatus `json:"status,omitempty"`
}

type WorkflowList struct {
	Metadata ListMeta   `json:"metadata,omitempty"`
	Items    []Workflow `json:"items,omitempty"`
}

type CronWorkflowSpec struct {
	Schedule  string   `json:"schedule,omitempty"`
	Schedules []string `json:"schedules,omitempty"`
	Timezone  string   `json:"timezone,omitempty"`
	Suspend   bool     `json:"suspend,omitempty"`
}

type CronWorkflowStatus struct {
	LastScheduledTime string `json:"lastScheduledTime,omitempty"`
	NextScheduledTime string `json:"nextScheduledTime,omitempty"`
}

type CronWorkflow struct {
	Metadata ObjectMeta         `json:"metadata,omitempty"`
	Spec     CronWorkflowSpec   `json:"spec,omitempty"`
	Status   CronWorkflowStatus `json:"status,omitempty"`
}

type CronWorkflowList struct {
	Items []CronWorkflow `json:"items,omitempty"`
}

type WorkflowTemplate struct {
	Metadata ObjectMeta   `json:"metadata,omitempty"`
	Spec     WorkflowSpec `json:"spec,omitempty"`
}

type WorkflowTemplateList struct {
	Items []WorkflowTemplate `json:"items,omitempty"`
}

type ClusterWorkflowTemplate struct {
	Metadata ObjectMeta   `json:"metadata,omitempty"`
	Spec     WorkflowSpec `json:"spec,omitempty"`
}

type ClusterWorkflowTemplateList struct {
	Items []ClusterWorkflowTemplate `json:"items,omitempty"`
}

type WorkflowRetryRequest struct {
	Name              string `json:"name"`
	Namespace         string `json:"namespace"`
	RestartSuccessful bool   `json:"restartSuccessful"`
}

type WorkflowTerminateRequest struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type CronWorkflowSuspendRequest struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type CronWorkflowResumeRequest struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}
