// Code generated by go run ./cmd/generate-argo-models; DO NOT EDIT.
// Source: Argo Workflows v3.7.3 Swagger projection.

package models

import "encoding/json"

type ObjectMeta struct {
	Name        string            `json:"name,omitempty"`
	Namespace   string            `json:"namespace,omitempty"`
	UID         string            `json:"uid,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

type ListMeta struct {
	Continue string `json:"continue,omitempty"`
}

type Event struct {
	Type           string `json:"type,omitempty"`
	Reason         string `json:"reason,omitempty"`
	Message        string `json:"message,omitempty"`
	Count          int    `json:"count,omitempty"`
	FirstTimestamp string `json:"firstTimestamp,omitempty"`
	LastTimestamp  string `json:"lastTimestamp,omitempty"`
	EventTime      string `json:"eventTime,omitempty"`
}

type Parameter struct {
	Name      string          `json:"name,omitempty"`
	Value     json.RawMessage `json:"value,omitempty"`
	Default   json.RawMessage `json:"default,omitempty"`
	ValueFrom json.RawMessage `json:"valueFrom,omitempty"`
}

type Arguments struct {
	Parameters []Parameter `json:"parameters,omitempty"`
}

type Artifact struct {
	Name     string `json:"name,omitempty"`
	Path     string `json:"path,omitempty"`
	Optional bool   `json:"optional,omitempty"`
}

type Inputs struct {
	Artifacts []Artifact `json:"artifacts,omitempty"`
}

type Outputs struct {
	Parameters []Parameter `json:"parameters,omitempty"`
	Artifacts  []Artifact  `json:"artifacts,omitempty"`
}

type NodeStatus struct {
	ID           string   `json:"id,omitempty"`
	Name         string   `json:"name,omitempty"`
	DisplayName  string   `json:"displayName,omitempty"`
	Type         string   `json:"type,omitempty"`
	Phase        string   `json:"phase,omitempty"`
	TemplateName string   `json:"templateName,omitempty"`
	BoundaryID   string   `json:"boundaryID,omitempty"`
	Children     []string `json:"children,omitempty"`
	StartedAt    string   `json:"startedAt,omitempty"`
	FinishedAt   string   `json:"finishedAt,omitempty"`
	Message      string   `json:"message,omitempty"`
	Inputs       Inputs   `json:"inputs,omitempty"`
	Outputs      Outputs  `json:"outputs,omitempty"`
}

type Template struct {
	Name string `json:"name,omitempty"`
}

type WorkflowSpec struct {
	Arguments  Arguments  `json:"arguments,omitempty"`
	Entrypoint string     `json:"entrypoint,omitempty"`
	Templates  []Template `json:"templates,omitempty"`
}

type WorkflowStatus struct {
	Phase      string                `json:"phase,omitempty"`
	Progress   string                `json:"progress,omitempty"`
	StartedAt  string                `json:"startedAt,omitempty"`
	FinishedAt string                `json:"finishedAt,omitempty"`
	Message    string                `json:"message,omitempty"`
	Nodes      map[string]NodeStatus `json:"nodes,omitempty"`
	Outputs    Outputs               `json:"outputs,omitempty"`
}

type Workflow struct {
	Metadata ObjectMeta     `json:"metadata,omitempty"`
	Spec     WorkflowSpec   `json:"spec,omitempty"`
	Status   WorkflowStatus `json:"status,omitempty"`
}

type WorkflowList struct {
	Metadata ListMeta   `json:"metadata,omitempty"`
	Items    []Workflow `json:"items,omitempty"`
}

type CronWorkflowSpec struct {
	Schedule  string   `json:"schedule,omitempty"`
	Schedules []string `json:"schedules,omitempty"`
	Timezone  string   `json:"timezone,omitempty"`
	Suspend   bool     `json:"suspend,omitempty"`
}

type CronWorkflowStatus struct {
	LastScheduledTime string `json:"lastScheduledTime,omitempty"`
	NextScheduledTime string `json:"nextScheduledTime,omitempty"`
}

type CronWorkflow struct {
	Metadata ObjectMeta         `json:"metadata,omitempty"`
	Spec     CronWorkflowSpec   `json:"spec,omitempty"`
	Status   CronWorkflowStatus `json:"status,omitempty"`
}

type CronWorkflowList struct {
	Metadata ListMeta       `json:"metadata,omitempty"`
	Items    []CronWorkflow `json:"items,omitempty"`
}

type WorkflowTemplate struct {
	Metadata ObjectMeta   `json:"metadata,omitempty"`
	Spec     WorkflowSpec `json:"spec,omitempty"`
}

type WorkflowTemplateList struct {
	Metadata ListMeta           `json:"metadata,omitempty"`
	Items    []WorkflowTemplate `json:"items,omitempty"`
}

type ClusterWorkflowTemplate struct {
	Metadata ObjectMeta   `json:"metadata,omitempty"`
	Spec     WorkflowSpec `json:"spec,omitempty"`
}

type ClusterWorkflowTemplateList struct {
	Metadata ListMeta                  `json:"metadata,omitempty"`
	Items    []ClusterWorkflowTemplate `json:"items,omitempty"`
}

type SubmitOpts struct {
	Parameters []string `json:"parameters,omitempty"`
}

type WorkflowSubmitRequest struct {
	Namespace     string     `json:"namespace"`
	ResourceKind  string     `json:"resourceKind"`
	ResourceName  string     `json:"resourceName"`
	SubmitOptions SubmitOpts `json:"submitOptions"`
}

type WorkflowResubmitRequest struct {
	Name       string   `json:"name"`
	Namespace  string   `json:"namespace"`
	Memoized   bool     `json:"memoized"`
	Parameters []string `json:"parameters"`
}

type WorkflowSuspendRequest struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type WorkflowResumeRequest struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type WorkflowLintRequest struct {
	Namespace string          `json:"namespace"`
	Workflow  json.RawMessage `json:"workflow"`
}

type WorkflowTemplateLintRequest struct {
	Namespace string          `json:"namespace"`
	Template  json.RawMessage `json:"template"`
}

type ClusterWorkflowTemplateLintRequest struct {
	Template json.RawMessage `json:"template"`
}

type WorkflowRetryRequest struct {
	Name              string `json:"name"`
	Namespace         string `json:"namespace"`
	RestartSuccessful bool   `json:"restartSuccessful"`
}

type WorkflowTerminateRequest struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type CronWorkflowSuspendRequest struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

type CronWorkflowResumeRequest struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}
